//! Movie Types
export const FETCH_MOVIES = "FETCH_MOVIES";
export const ADD_MOVIE = "ADD_MOVIE";
export const REMOVE_MOVIE = "REMOVE_MOVIE";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const SINGLE_MOVIE = "SINGLE_MOVIE";
export const FETCH_POPULAR_MOVIES = "FETCH_POPULAR_MOVIES";
export const FETCH_TOP_RATED_MOVIES = "FETCH_TOP_RATED_MOVIES";
export const FETCH_UPCOMING_MOVIES = "FETCH_UPCOMING_MOVIES";
export const EMPTY_CURRENT_MOVIE = "EMPTY_CURRENT_MOVIE";

//! Error Types
export const RETURN_ERROR = "RETURN_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//! List Types
export const FETCH_LIST_DETAILS = "FETCH_LIST_DETAILS";
